name: metax
channels:
  - zldeng
  - conda-forge
  - bioconda
dependencies:
  - metax>=0.9.12
  - python>=3.9
  - pandas>=1.3
  - numpy>=1.20
  - pip:
    - ete3>=3.1.2
    - click>=8.0
    - rich-click>=1.0
    - biopython>=1.79
