import type { FormFieldDefinition } from "@/types/form-config";
import {
  STUDY_INFORMATION_SECTION_ID,
  STUDY_METADATA_SECTION_ID,
} from "@/lib/studies/fixed-sections";

// Technical (non-patient) per-study questionnaire for the synthetic IBD demo study.
// Showcases the dynamic-studies module with SEQUENCING / LIBRARY / QC / BIOINFORMATICS
// fields — deliberately NOT patient characteristics — to reinforce that SeqDesk captures
// technical sequencing metadata, not private patient data. Per-sample answers persist in
// Sample.checklistData keyed by field name; study-level answers in Study.studyMetadata.
export const IBD_STUDY_FORM_FIELDS: FormFieldDefinition[] = [
  {
    id: "field_ibd_sample_association",
    type: "text",
    label: "Sample Association",
    name: "_sample_association",
    required: false,
    visible: true,
    helpText: "Interface to associate samples from orders to this study",
    order: 0,
  },
  {
    id: "field_ibd_pi",
    type: "text",
    label: "Principal Investigator",
    name: "principal_investigator",
    required: false,
    visible: true,
    helpText: "Lead researcher responsible for this study",
    order: 1,
    groupId: STUDY_INFORMATION_SECTION_ID,
    perSample: false,
  },
  {
    id: "field_ibd_abstract",
    type: "textarea",
    label: "Study Abstract",
    name: "study_abstract",
    required: false,
    visible: true,
    helpText: "Brief description of the study",
    order: 2,
    groupId: STUDY_INFORMATION_SECTION_ID,
    perSample: false,
  },
  {
    id: "field_ibd_target_depth",
    type: "textarea",
    label: "Target Sequencing Depth",
    name: "target_sequencing_depth",
    required: false,
    visible: true,
    helpText: "Planned sequencing output/depth per library for this study (technical run-planning metadata, not patient data).",
    order: 3,
    groupId: STUDY_INFORMATION_SECTION_ID,
    perSample: false,
  },
  {
    id: "field_ibd_qc_pipeline",
    type: "textarea",
    label: "QC / Bioinformatics Pipeline",
    name: "qc_pipeline_version",
    required: false,
    visible: true,
    helpText: "Read-cleaning, host-depletion and QC pipeline applied to this study's libraries, plus per-batch controls (bioinformatics provenance).",
    order: 4,
    groupId: STUDY_INFORMATION_SECTION_ID,
    perSample: false,
  },
  {
    id: "field_ibd_mixs",
    type: "mixs",
    label: "MIxS Metadata",
    name: "_mixs",
    required: false,
    visible: true,
    helpText: "Environment-specific metadata fields following MIxS standards",
    order: 5,
    groupId: STUDY_METADATA_SECTION_ID,
    perSample: false,
    moduleSource: "mixs-metadata",
  },
  // ── per-sample technical fields (sequencing / library / QC / bioinformatics) ──
  {
    id: "field_ibd_dna_extraction_kit",
    type: "select",
    label: "DNA Extraction Kit",
    name: "dna_extraction_kit",
    required: true,
    visible: true,
    helpText: "Commercial kit used to extract total genomic DNA from the specimen. Stool specimens use a bead-beating faecal kit; mucosal biopsies use a host-depleting microbiome kit. Wet-lab metadata, not patient data.",
    order: 0,
    perSample: true,
    options: [
      { value: "QIAamp PowerFecal Pro DNA Kit", label: "QIAamp PowerFecal Pro DNA Kit" },
      { value: "QIAamp DNA Microbiome Kit", label: "QIAamp DNA Microbiome Kit" },
      { value: "ZymoBIOMICS DNA Miniprep", label: "ZymoBIOMICS DNA Miniprep" },
      { value: "MagAttract PowerMicrobiome", label: "MagAttract PowerMicrobiome" },
      { value: "Other", label: "Other" },
    ],
  },
  {
    id: "field_ibd_library_prep_kit",
    type: "select",
    label: "Library Preparation Kit",
    name: "library_prep_kit",
    required: true,
    visible: true,
    helpText: "Library construction chemistry for this library. Short-read libraries use Illumina DNA Prep tagmentation; long-read libraries use the Nanopore ligation kit. Sequencing wet-lab metadata only.",
    order: 1,
    perSample: true,
    options: [
      { value: "Illumina DNA Prep (tagmentation)", label: "Illumina DNA Prep (tagmentation)" },
      { value: "Illumina DNA PCR-Free", label: "Illumina DNA PCR-Free" },
      { value: "NEBNext Ultra II FS", label: "NEBNext Ultra II FS" },
      { value: "Nanopore Ligation Sequencing Kit (SQK-LSK114)", label: "Nanopore Ligation Sequencing Kit (SQK-LSK114)" },
      { value: "Nanopore Rapid Barcoding (SQK-RBK114.96)", label: "Nanopore Rapid Barcoding (SQK-RBK114.96)" },
    ],
  },
  {
    id: "field_ibd_library_insert_size_bp",
    type: "number",
    label: "Library Insert Size (bp)",
    name: "library_insert_size_bp",
    required: false,
    visible: true,
    helpText: "Mean fragment insert size of the prepared library in base pairs (Illumina). For long-read native libraries this is the input fragment N50 in bp. Library QC metric.",
    order: 2,
    perSample: true,
  },
  {
    id: "field_ibd_sequencing_platform",
    type: "select",
    label: "Sequencing Platform / Flow Cell",
    name: "sequencing_platform",
    required: true,
    visible: true,
    helpText: "Instrument and flow cell used for this library. Baseline and follow-up libraries ran on Illumina NovaSeq 6000; long-read libraries ran on Oxford Nanopore PromethION. Run-tracking metadata, not clinical.",
    order: 3,
    perSample: true,
    options: [
      { value: "Illumina NovaSeq 6000 (S4 flow cell)", label: "Illumina NovaSeq 6000 (S4 flow cell)" },
      { value: "Illumina NovaSeq X Plus (10B)", label: "Illumina NovaSeq X Plus (10B)" },
      { value: "Illumina NextSeq 2000", label: "Illumina NextSeq 2000" },
      { value: "Oxford Nanopore PromethION (R10.4.1)", label: "Oxford Nanopore PromethION (R10.4.1)" },
      { value: "Oxford Nanopore GridION (R10.4.1)", label: "Oxford Nanopore GridION (R10.4.1)" },
    ],
  },
  {
    id: "field_ibd_read_configuration",
    type: "text",
    label: "Read Configuration / Chemistry",
    name: "read_configuration",
    required: false,
    visible: true,
    helpText: "Run mode and chemistry, e.g. Illumina paired-end read length and chemistry version, or Nanopore pore chemistry (R10.4.1, kit14). Technical run configuration.",
    order: 4,
    perSample: true,
  },
  {
    id: "field_ibd_basecaller_version",
    type: "text",
    label: "Basecaller / Demux Software + Version",
    name: "basecaller_version",
    required: false,
    visible: true,
    helpText: "Software and version that produced reads from raw signal/BCL. Illumina: BCL Convert / DRAGEN version. Nanopore: Dorado basecaller version and model. Bioinformatics provenance.",
    order: 5,
    perSample: true,
  },
  {
    id: "field_ibd_host_depletion_method",
    type: "select",
    label: "Host-Read Depletion Method",
    name: "host_depletion_method",
    required: true,
    visible: true,
    helpText: "Computational removal of human host reads before microbiome analysis (privacy-protective step). Short reads mapped with bwa-mem2; long reads mapped with minimap2 against the human reference. No host genotype is retained.",
    order: 6,
    perSample: true,
    options: [
      { value: "bwa-mem2 vs T2T-CHM13v2.0", label: "bwa-mem2 vs T2T-CHM13v2.0" },
      { value: "bwa-mem2 vs GRCh38", label: "bwa-mem2 vs GRCh38" },
      { value: "minimap2 vs T2T-CHM13v2.0", label: "minimap2 vs T2T-CHM13v2.0" },
      { value: "Bowtie2 vs GRCh38", label: "Bowtie2 vs GRCh38" },
      { value: "Kraken2 host filter", label: "Kraken2 host filter" },
      { value: "None", label: "None" },
    ],
  },
  {
    id: "field_ibd_pct_host_reads_removed",
    type: "number",
    label: "% Host Reads Removed",
    name: "pct_host_reads_removed",
    required: false,
    visible: true,
    helpText: "Percentage of raw reads identified as human host and discarded during depletion. Mucosal-biopsy libraries carry a much higher host fraction than stool. Bioinformatics QC metric.",
    order: 7,
    perSample: true,
  },
  {
    id: "field_ibd_raw_read_count",
    type: "number",
    label: "Raw Read Count",
    name: "raw_read_count",
    required: false,
    visible: true,
    helpText: "Number of reads (Illumina: read pairs; Nanopore: reads) produced by the instrument before any QC, adapter trimming, or host depletion. QC quantity metric.",
    order: 8,
    perSample: true,
  },
  {
    id: "field_ibd_qc_read_count",
    type: "number",
    label: "QC-Passed Read Count",
    name: "qc_read_count",
    required: false,
    visible: true,
    helpText: "Reads remaining after adapter/quality trimming and host-read depletion — the analysis-ready microbial read set. Bioinformatics QC metric.",
    order: 9,
    perSample: true,
  },
  {
    id: "field_ibd_mean_q30_or_qscore",
    type: "text",
    label: "Mean Q30 % (Illumina) / Mean Q-score (Nanopore)",
    name: "mean_q30_or_qscore",
    required: false,
    visible: true,
    helpText: "Per-library base-quality summary. Illumina libraries report % of bases at or above Q30; Nanopore libraries report mean read Q-score (Phred). Sequencing QC metric. Text because the two platforms report different units.",
    order: 10,
    perSample: true,
  },
  {
    id: "field_ibd_control_type",
    type: "select",
    label: "Run Control Type",
    name: "control_type",
    required: false,
    visible: true,
    helpText: "Whether this library is a biological specimen or a process control. Negative (extraction blank / no-template) and positive (mock community) controls are run per batch to monitor contamination and bias. QC provenance, not patient data.",
    order: 11,
    perSample: true,
    options: [
      { value: "specimen", label: "specimen" },
      { value: "negative extraction control", label: "negative extraction control" },
      { value: "no-template control", label: "no-template control" },
      { value: "positive control (ZymoBIOMICS mock community)", label: "positive control (ZymoBIOMICS mock community)" },
    ],
  },
];

// Per-sample technical answers, keyed by sampleAlias -> { fieldName: value }. Merged into
// each IBD Sample.checklistData at seed time (alongside the MIxS registry keys).
export const IBD_STUDY_FORM_SAMPLE_VALUES: Record<string, Record<string, string>> = {
  "IBD-CD-01": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "412",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "4.8",
    raw_read_count: "41250433",
    qc_read_count: "38967104",
    mean_q30_or_qscore: "93.4% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-CD-02": {
    dna_extraction_kit: "QIAamp DNA Microbiome Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "388",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "61.3",
    raw_read_count: "28117905",
    qc_read_count: "10489216",
    mean_q30_or_qscore: "92.7% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-UC-01": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "405",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "5.6",
    raw_read_count: "39884217",
    qc_read_count: "37460108",
    mean_q30_or_qscore: "93.1% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-UC-02": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "418",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "6.1",
    raw_read_count: "37551060",
    qc_read_count: "35112447",
    mean_q30_or_qscore: "93.0% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-HC-01": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "409",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "4.2",
    raw_read_count: "43002884",
    qc_read_count: "40872551",
    mean_q30_or_qscore: "93.6% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-HC-02": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "415",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "4.5",
    raw_read_count: "40119673",
    qc_read_count: "38109284",
    mean_q30_or_qscore: "93.5% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-CD-01-W12": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "410",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "5.1",
    raw_read_count: "38760221",
    qc_read_count: "36490817",
    mean_q30_or_qscore: "93.2% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-UC-01-W12": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Illumina DNA Prep (tagmentation)",
    library_insert_size_bp: "406",
    sequencing_platform: "Illumina NovaSeq 6000 (S4 flow cell)",
    read_configuration: "2x150 bp paired-end, NovaSeq 6000 v1.5 chemistry",
    basecaller_version: "DRAGEN BCL Convert 4.2.7",
    host_depletion_method: "bwa-mem2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "5.4",
    raw_read_count: "41002558",
    qc_read_count: "38563990",
    mean_q30_or_qscore: "93.3% bases >= Q30",
    control_type: "specimen",
  },
  "IBD-CD-01-LR": {
    dna_extraction_kit: "QIAamp PowerFecal Pro DNA Kit",
    library_prep_kit: "Nanopore Ligation Sequencing Kit (SQK-LSK114)",
    library_insert_size_bp: "8420",
    sequencing_platform: "Oxford Nanopore PromethION (R10.4.1)",
    read_configuration: "R10.4.1 / kit14, native ligation, single PromethION flow cell",
    basecaller_version: "Dorado 0.7.2 (dna_r10.4.1_e8.2_400bps_sup@v5.0.0)",
    host_depletion_method: "minimap2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "",
    raw_read_count: "",
    qc_read_count: "",
    mean_q30_or_qscore: "planned (not yet sequenced)",
    control_type: "specimen",
  },
  "IBD-CD-02-LR": {
    dna_extraction_kit: "QIAamp DNA Microbiome Kit",
    library_prep_kit: "Nanopore Ligation Sequencing Kit (SQK-LSK114)",
    library_insert_size_bp: "7150",
    sequencing_platform: "Oxford Nanopore PromethION (R10.4.1)",
    read_configuration: "R10.4.1 / kit14, native ligation, single PromethION flow cell",
    basecaller_version: "Dorado 0.7.2 (dna_r10.4.1_e8.2_400bps_sup@v5.0.0)",
    host_depletion_method: "minimap2 vs T2T-CHM13v2.0",
    pct_host_reads_removed: "",
    raw_read_count: "",
    qc_read_count: "",
    mean_q30_or_qscore: "planned (not yet sequenced)",
    control_type: "specimen",
  },
};

// Study-level technical answers, merged into Study.studyMetadata.
export const IBD_STUDY_FORM_STUDY_VALUES: Record<string, string> = {
  target_sequencing_depth: "20 Gbp per stool library (~10 Gbp microbial after host depletion); 5x PromethION flow cells reserved for long-read confirmation",
  qc_pipeline_version: "SeqDesk read-cleaning v2.1 (fastp 0.23.4 adapter/quality trimming + host depletion); positive control = ZymoBIOMICS D6300 mock community, negative = extraction blank per batch",
};
