import crypto from "node:crypto";
import { createWriteStream } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { parseInputBindings } from "@/lib/explore/analyses";
import { parseStoredBlocks } from "@/lib/explore/report-blocks";
import { resolveContainedPath, resolveExploreStorage } from "@/lib/explore/storage";
import { EXPLORE_SENSITIVITIES, type ExploreSensitivity } from "@/lib/explore/types";
import { canImportFileAsTable, MAX_LIBRARY_FILE_BYTES, parseStoredFileBindings, type AnalysisFileBinding, type LibraryFileSummary } from "./library-types";

export class FileLibraryError extends Error {
  constructor(public status: number, message: string) { super(message); }
}

async function libraryRoot(): Promise<string> {
  const storage = await resolveExploreStorage();
  const root = path.join(storage.importsRoot, "files");
  await fs.mkdir(root, { recursive: true });
  return root;
}

/** The original name is metadata; the storage path is generated by the server. */
export async function storeLibraryFile(input: { targetKey: string; file: File; createdById: string }) {
  if (input.file.size > MAX_LIBRARY_FILE_BYTES) throw new FileLibraryError(413, "Files must be 100 MB or smaller.");
  const originalName = input.file.name.split(/[\\/]/).pop()?.replace(/\p{Cc}/gu, "").trim().slice(0, 240) || "file";
  const buffer = Buffer.from(await input.file.arrayBuffer());
  if (buffer.length > MAX_LIBRARY_FILE_BYTES) throw new FileLibraryError(413, "Files must be 100 MB or smaller.");
  const storagePath = crypto.randomUUID();
  const root = await libraryRoot();
  const destination = path.join(root, storagePath);
  await fs.writeFile(destination, buffer, { flag: "wx", mode: 0o600 });
  try {
    return await db.managedFile.create({ data: {
      targetKey: input.targetKey, originalName, storagePath,
      mimeType: input.file.type || "application/octet-stream",
      sizeBytes: BigInt(buffer.length),
      checksumSha256: crypto.createHash("sha256").update(buffer).digest("hex"),
      createdById: input.createdById,
    } });
  } catch (error) {
    await fs.unlink(destination).catch(() => {});
    throw error;
  }
}

/** Largest streamed upload (raw request body); the multipart route keeps its 100 MB limit. */
export const MAX_STREAM_UPLOAD_BYTES = Number(process.env.SEQDESK_MAX_UPLOAD_BYTES) > 0 ? Number(process.env.SEQDESK_MAX_UPLOAD_BYTES) : 20 * 1024 * 1024 * 1024;

/**
 * Store an upload that arrives as a byte stream (the request body): written to disk as it comes, hashed on the
 * way, never held in memory. Stops with 413 past `maxBytes`, and removes the partial file on any error.
 */
export async function storeLibraryFileStream(input: { targetKey: string; name: string; mimeType?: string | null; body: AsyncIterable<Uint8Array>; createdById: string; maxBytes?: number }) {
  const maxBytes = input.maxBytes ?? MAX_STREAM_UPLOAD_BYTES;
  const originalName = input.name.split(/[\\/]/).pop()?.replace(/\p{Cc}/gu, "").trim().slice(0, 240) || "file";
  const storagePath = crypto.randomUUID();
  const root = await libraryRoot();
  const destination = path.join(root, storagePath);
  const out = createWriteStream(destination, { flags: "wx", mode: 0o600 });
  const hash = crypto.createHash("sha256");
  let size = 0;
  try {
    for await (const chunk of input.body) {
      size += chunk.byteLength;
      if (size > maxBytes) throw new FileLibraryError(413, `Files must be ${Math.round(maxBytes / 1024 / 1024 / 1024 * 10) / 10} GB or smaller.`);
      // The request body may reuse its chunk buffers once the next chunk is read; the file gets its own copy.
      const bytes = Buffer.from(chunk);
      hash.update(bytes);
      if (!out.write(bytes)) await new Promise<void>((resolve, reject) => {
        const done = (error?: Error) => { out.off("drain", done); out.off("error", done); if (error) reject(error); else resolve(); };
        out.on("drain", done);
        out.on("error", done);
      });
    }
    await new Promise<void>((resolve, reject) => out.end((error?: Error | null) => (error ? reject(error) : resolve())));
    if (size === 0) throw new FileLibraryError(400, "The file is empty.");
    return await db.managedFile.create({ data: {
      targetKey: input.targetKey, originalName, storagePath,
      mimeType: input.mimeType || "application/octet-stream",
      sizeBytes: BigInt(size),
      checksumSha256: hash.digest("hex"),
      createdById: input.createdById,
    } });
  } catch (error) {
    out.destroy();
    await fs.unlink(destination).catch(() => {});
    throw error;
  }
}

/** Where a stored file lives, for readers that stream it (large tables) instead of loading it. */
export async function libraryFilePath(file: { storagePath: string }): Promise<string> {
  const root = await libraryRoot();
  try { return await resolveContainedPath(root, file.storagePath); }
  catch { throw new FileLibraryError(404, "The original file is unavailable in Files."); }
}

export async function getLibraryFile(id: string) {
  const file = await db.managedFile.findUnique({ where: { id } });
  if (!file) throw new FileLibraryError(404, "File not found");
  return file;
}

export async function readLibraryFile(file: { storagePath: string; checksumSha256: string }) {
  const root = await libraryRoot();
  let absolutePath: string;
  try { absolutePath = await resolveContainedPath(root, file.storagePath); }
  catch { throw new FileLibraryError(404, "The original file is unavailable in Files."); }
  const buffer = await fs.readFile(absolutePath);
  if (crypto.createHash("sha256").update(buffer).digest("hex") !== file.checksumSha256) {
    throw new FileLibraryError(409, "The original file has changed on disk. Upload it again before using it.");
  }
  return buffer;
}

/** Files, imported tables and the reports that reference them, limited to one authorized scope. */
export async function listLibraryFiles(targetKey: string): Promise<LibraryFileSummary[]> {
  const [files, reports] = await Promise.all([
    db.managedFile.findMany({ where: { targetKey, removedAt: null }, orderBy: { createdAt: "desc" }, include: { datasets: { select: { id: true, name: true } }, reports: { select: { reportId: true } } } }),
    db.exploreReport.findMany({ where: { targetKey }, select: {
      id: true, title: true, blocks: true,
      analyses: { select: { revisions: { select: { inputs: true, fileInputs: true } } } },
    } }),
  ]);
  const usage = reports.map((report) => ({
    id: report.id, title: report.title,
    datasetIds: new Set([
      ...parseStoredBlocks(report.blocks).flatMap((block) => "datasetId" in block ? [block.datasetId] : []),
      ...report.analyses.flatMap((analysis) => analysis.revisions.flatMap((revision) => parseInputBindings(revision.inputs).map((entry) => entry.datasetId))),
    ]),
    fileIds: new Set(report.analyses.flatMap((analysis) => analysis.revisions.flatMap((revision) => parseStoredFileBindings(revision.fileInputs).map((entry) => entry.fileId)))),
  }));
  return files.map((file) => ({
    id: file.id, targetKey: file.targetKey, originalName: file.originalName,
    mimeType: file.mimeType, sizeBytes: Number(file.sizeBytes), checksumSha256: file.checksumSha256,
    createdAt: file.createdAt.toISOString(), canImportTable: canImportFileAsTable(file.originalName),
    description: file.description, tags: file.tags, sensitivity: fileSensitivity(file),
    datasets: file.datasets,
    reports: usage.map((report) => ({
      id: report.id, title: report.title,
      attached: file.reports.some((link) => link.reportId === report.id),
      usedInReport: report.fileIds.has(file.id) || file.datasets.some((dataset) => report.datasetIds.has(dataset.id)),
    })).filter((report) => report.attached || report.usedInReport),
  }));
}

export async function validateFileBindings(raw: unknown, targetKey: string): Promise<AnalysisFileBinding[]> {
  if (raw === undefined) return [];
  if (!Array.isArray(raw) || raw.length > 50) throw new FileLibraryError(400, "Choose up to 50 file inputs.");
  const bindings = parseStoredFileBindings(JSON.stringify(raw));
  if (bindings.length !== raw.length || new Set(bindings.map((entry) => entry.alias)).size !== bindings.length) {
    throw new FileLibraryError(400, "Each file input needs a unique alias using lowercase letters, numbers and underscores.");
  }
  if (bindings.length === 0) return [];
  const files = await db.managedFile.findMany({ where: { id: { in: bindings.map((entry) => entry.fileId) }, targetKey, removedAt: null }, select: { id: true } });
  const ids = new Set(files.map((file) => file.id));
  if (bindings.some((binding) => !ids.has(binding.fileId))) throw new FileLibraryError(400, "A selected file does not belong to this study or order, or was removed.");
  return bindings;
}

/** Each run receives a verified copy, so analyses cannot change the original upload. */
export async function stageLibraryFileInputs(runFolder: string, targetKey: string, raw: unknown) {
  const bindings = await validateFileBindings(raw, targetKey);
  const staged: Record<string, { path: string; fileId: string; name: string; checksumSha256: string; sizeBytes: number }> = {};
  for (const binding of bindings) {
    const file = await getLibraryFile(binding.fileId);
    const bytes = await readLibraryFile(file);
    // Keep the original name, including compound extensions such as .fasta.gz.
    // A directory per alias keeps inputs with identical names separate.
    const basename = path.posix.basename(file.originalName.replace(/\\/g, "/"));
    const name = !basename || basename === "." || basename === ".." ? "file" : basename;
    const relativePath = path.posix.join("inputs", "files", binding.alias, name);
    await fs.mkdir(path.dirname(path.join(runFolder, relativePath)), { recursive: true });
    await fs.writeFile(path.join(runFolder, relativePath), bytes, { flag: "wx" });
    staged[binding.alias] = { path: relativePath, fileId: file.id, name: file.originalName, checksumSha256: file.checksumSha256, sizeBytes: bytes.length };
  }
  return staged;
}

/** The stored tier, read defensively so an unexpected value never breaks a listing. */
export function fileSensitivity(file: { sensitivity: string }): ExploreSensitivity {
  return EXPLORE_SENSITIVITIES.includes(file.sensitivity as ExploreSensitivity) ? (file.sensitivity as ExploreSensitivity) : "standard";
}

/** Notes on a file: what it is, tags to group it by, and the tier that tables read from it inherit. */
export async function updateLibraryFile(id: string, changes: { description?: string | null; tags?: string[]; sensitivity?: ExploreSensitivity }): Promise<LibraryFileSummary> {
  const file = await getLibraryFile(id);
  if (file.removedAt) throw new FileLibraryError(404, "File not found");
  await db.managedFile.update({ where: { id: file.id }, data: changes });
  const summary = (await listLibraryFiles(file.targetKey)).find((entry) => entry.id === file.id);
  if (!summary) throw new FileLibraryError(404, "File not found");
  return summary;
}

/** Removal hides the file from the study and blocks new uses; the bytes, tables and existing runs stay for provenance. */
export async function removeLibraryFile(id: string, removedById: string): Promise<void> {
  const file = await getLibraryFile(id);
  if (file.removedAt) return;
  await db.managedFile.update({ where: { id: file.id }, data: { removedAt: new Date(), removedById } });
}
