import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { parseInputBindings } from "@/lib/explore/analyses";
import { parseStoredBlocks } from "@/lib/explore/report-blocks";
import { resolveContainedPath, resolveExploreStorage } from "@/lib/explore/storage";
import { canImportFileAsTable, MAX_LIBRARY_FILE_BYTES, parseStoredFileBindings, type AnalysisFileBinding, type LibraryFileSummary } from "./library-types";

export class FileLibraryError extends Error {
  constructor(public status: number, message: string) { super(message); }
}

async function libraryRoot(): Promise<string> {
  const storage = await resolveExploreStorage();
  const root = path.join(storage.importsRoot, "files");
  await fs.mkdir(root, { recursive: true });
  return root;
}

/** The original name is metadata; the storage path is generated by the server. */
export async function storeLibraryFile(input: { targetKey: string; file: File; createdById: string }) {
  if (input.file.size > MAX_LIBRARY_FILE_BYTES) throw new FileLibraryError(413, "Files must be 100 MB or smaller.");
  const originalName = input.file.name.split(/[\\/]/).pop()?.replace(/\p{Cc}/gu, "").trim().slice(0, 240) || "file";
  const buffer = Buffer.from(await input.file.arrayBuffer());
  if (buffer.length > MAX_LIBRARY_FILE_BYTES) throw new FileLibraryError(413, "Files must be 100 MB or smaller.");
  const storagePath = crypto.randomUUID();
  const root = await libraryRoot();
  const destination = path.join(root, storagePath);
  await fs.writeFile(destination, buffer, { flag: "wx", mode: 0o600 });
  try {
    return await db.managedFile.create({ data: {
      targetKey: input.targetKey, originalName, storagePath,
      mimeType: input.file.type || "application/octet-stream",
      sizeBytes: BigInt(buffer.length),
      checksumSha256: crypto.createHash("sha256").update(buffer).digest("hex"),
      createdById: input.createdById,
    } });
  } catch (error) {
    await fs.unlink(destination).catch(() => {});
    throw error;
  }
}

export async function getLibraryFile(id: string) {
  const file = await db.managedFile.findUnique({ where: { id } });
  if (!file) throw new FileLibraryError(404, "File not found");
  return file;
}

export async function readLibraryFile(file: { storagePath: string; checksumSha256: string }) {
  const root = await libraryRoot();
  let absolutePath: string;
  try { absolutePath = await resolveContainedPath(root, file.storagePath); }
  catch { throw new FileLibraryError(404, "The original file is unavailable in Files."); }
  const buffer = await fs.readFile(absolutePath);
  if (crypto.createHash("sha256").update(buffer).digest("hex") !== file.checksumSha256) {
    throw new FileLibraryError(409, "The original file has changed on disk. Upload it again before using it.");
  }
  return buffer;
}

/** Files, imported tables and the reports that reference them, limited to one authorized scope. */
export async function listLibraryFiles(targetKey: string): Promise<LibraryFileSummary[]> {
  const [files, reports] = await Promise.all([
    db.managedFile.findMany({ where: { targetKey }, orderBy: { createdAt: "desc" }, include: { datasets: { select: { id: true, name: true } }, reports: { select: { reportId: true } } } }),
    db.exploreReport.findMany({ where: { targetKey }, select: {
      id: true, title: true, blocks: true,
      analyses: { select: { revisions: { select: { inputs: true, fileInputs: true } } } },
    } }),
  ]);
  const usage = reports.map((report) => ({
    id: report.id, title: report.title,
    datasetIds: new Set([
      ...parseStoredBlocks(report.blocks).flatMap((block) => "datasetId" in block ? [block.datasetId] : []),
      ...report.analyses.flatMap((analysis) => analysis.revisions.flatMap((revision) => parseInputBindings(revision.inputs).map((entry) => entry.datasetId))),
    ]),
    fileIds: new Set(report.analyses.flatMap((analysis) => analysis.revisions.flatMap((revision) => parseStoredFileBindings(revision.fileInputs).map((entry) => entry.fileId)))),
  }));
  return files.map((file) => ({
    id: file.id, targetKey: file.targetKey, originalName: file.originalName,
    mimeType: file.mimeType, sizeBytes: Number(file.sizeBytes), checksumSha256: file.checksumSha256,
    createdAt: file.createdAt.toISOString(), canImportTable: canImportFileAsTable(file.originalName),
    datasets: file.datasets,
    reports: usage.map((report) => ({
      id: report.id, title: report.title,
      attached: file.reports.some((link) => link.reportId === report.id),
      usedInReport: report.fileIds.has(file.id) || file.datasets.some((dataset) => report.datasetIds.has(dataset.id)),
    })).filter((report) => report.attached || report.usedInReport),
  }));
}

export async function validateFileBindings(raw: unknown, targetKey: string): Promise<AnalysisFileBinding[]> {
  if (raw === undefined) return [];
  if (!Array.isArray(raw) || raw.length > 50) throw new FileLibraryError(400, "Choose up to 50 file inputs.");
  const bindings = parseStoredFileBindings(JSON.stringify(raw));
  if (bindings.length !== raw.length || new Set(bindings.map((entry) => entry.alias)).size !== bindings.length) {
    throw new FileLibraryError(400, "Each file input needs a unique alias using lowercase letters, numbers and underscores.");
  }
  if (bindings.length === 0) return [];
  const files = await db.managedFile.findMany({ where: { id: { in: bindings.map((entry) => entry.fileId) }, targetKey }, select: { id: true } });
  const ids = new Set(files.map((file) => file.id));
  if (bindings.some((binding) => !ids.has(binding.fileId))) throw new FileLibraryError(400, "A selected file does not belong to this study or order.");
  return bindings;
}

/** Each run receives a verified copy, so analyses cannot change the original upload. */
export async function stageLibraryFileInputs(runFolder: string, targetKey: string, raw: unknown) {
  const bindings = await validateFileBindings(raw, targetKey);
  const staged: Record<string, { path: string; fileId: string; name: string; checksumSha256: string; sizeBytes: number }> = {};
  for (const binding of bindings) {
    const file = await getLibraryFile(binding.fileId);
    const bytes = await readLibraryFile(file);
    // Keep the original name, including compound extensions such as .fasta.gz.
    // A directory per alias keeps inputs with identical names separate.
    const basename = path.posix.basename(file.originalName.replace(/\\/g, "/"));
    const name = !basename || basename === "." || basename === ".." ? "file" : basename;
    const relativePath = path.posix.join("inputs", "files", binding.alias, name);
    await fs.mkdir(path.dirname(path.join(runFolder, relativePath)), { recursive: true });
    await fs.writeFile(path.join(runFolder, relativePath), bytes, { flag: "wx" });
    staged[binding.alias] = { path: relativePath, fileId: file.id, name: file.originalName, checksumSha256: file.checksumSha256, sizeBytes: bytes.length };
  }
  return staged;
}
