// Generic Nextflow DAG Parser
// Parses the .dot file generated by `nextflow run -with-dag dag.dot`

import fs from 'fs/promises';

export interface DagNode {
  id: string;
  label: string;
  process: string;      // Extracted process name
  type: 'process' | 'operator' | 'origin' | 'terminal';
}

export interface DagEdge {
  from: string;
  to: string;
  label?: string;
}

export interface NextflowDag {
  nodes: Map<string, DagNode>;
  edges: DagEdge[];
  // Process-level DAG (aggregated)
  processNodes: string[];
  processEdges: { from: string; to: string }[];
}

/**
 * Parse a Nextflow DAG file (.dot format)
 */
export async function parseDagFile(dagPath: string): Promise<NextflowDag> {
  const content = await fs.readFile(dagPath, 'utf-8');
  return parseDagContent(content);
}

/**
 * Parse DAG content directly
 */
export function parseDagContent(content: string): NextflowDag {
  const nodes = new Map<string, DagNode>();
  const edges: DagEdge[] = [];

  // Parse node definitions: p0 [label="FASTQC"];
  const nodeRegex = /(\w+)\s*\[([^\]]+)\]/g;
  let match;

  while ((match = nodeRegex.exec(content)) !== null) {
    const id = match[1];
    const attrs = parseAttributes(match[2]);
    const label = attrs.label || id;

    // Determine node type from shape or label
    let type: DagNode['type'] = 'process';
    if (attrs.shape === 'point' || label === '' || label === 'origin') {
      type = 'origin';
    } else if (attrs.shape === 'doublecircle' || label === 'terminal') {
      type = 'terminal';
    } else if (label.startsWith('Channel.') || attrs.shape === 'box') {
      type = 'operator';
    }

    // Extract process name (remove NFCORE_XXX: prefix)
    const process = extractProcessName(label);

    nodes.set(id, { id, label, process, type });
  }

  // Parse edge definitions: p0 -> p1 [label="reads"];
  const edgeRegex = /(\w+)\s*->\s*(\w+)(?:\s*\[([^\]]*)\])?/g;

  while ((match = edgeRegex.exec(content)) !== null) {
    const from = match[1];
    const to = match[2];
    const attrs = match[3] ? parseAttributes(match[3]) : {};

    edges.push({
      from,
      to,
      label: attrs.label,
    });
  }

  // Build process-level DAG by filtering to just process nodes
  const processNodes = Array.from(nodes.values())
    .filter((n) => n.type === 'process')
    .map((n) => n.process);

  // Build process edges by traversing through operators
  const processEdges = buildProcessEdges(nodes, edges);

  return {
    nodes,
    edges,
    processNodes: [...new Set(processNodes)],
    processEdges,
  };
}

/**
 * Parse DOT attribute string into key-value pairs
 */
function parseAttributes(attrString: string): Record<string, string> {
  const attrs: Record<string, string> = {};

  // Match key=value or key="value" pairs
  const attrRegex = /(\w+)\s*=\s*(?:"([^"]*)"|(\S+))/g;
  let match;

  while ((match = attrRegex.exec(attrString)) !== null) {
    const key = match[1];
    const value = match[2] !== undefined ? match[2] : match[3];
    attrs[key] = value;
  }

  return attrs;
}

/**
 * Extract clean process name from label
 * "NFCORE_MAG:MAG:FASTQC" -> "FASTQC"
 */
function extractProcessName(label: string): string {
  // Remove any workflow prefix (e.g., NFCORE_MAG:MAG:)
  const parts = label.split(':');
  return parts[parts.length - 1] || label;
}

/**
 * Build process-to-process edges by traversing through operators
 * This gives us the actual data flow between processes
 */
function buildProcessEdges(
  nodes: Map<string, DagNode>,
  edges: DagEdge[]
): { from: string; to: string }[] {
  const processEdges: { from: string; to: string }[] = [];
  const seen = new Set<string>();

  // Build adjacency list
  const adj = new Map<string, string[]>();
  for (const edge of edges) {
    if (!adj.has(edge.from)) adj.set(edge.from, []);
    adj.get(edge.from)!.push(edge.to);
  }

  // For each process node, find reachable process nodes
  for (const [nodeId, node] of nodes) {
    if (node.type !== 'process') continue;

    // BFS to find connected process nodes
    const visited = new Set<string>();
    const queue = adj.get(nodeId) || [];

    while (queue.length > 0) {
      const current = queue.shift()!;
      if (visited.has(current)) continue;
      visited.add(current);

      const currentNode = nodes.get(current);
      if (!currentNode) continue;

      if (currentNode.type === 'process') {
        const edgeKey = `${node.process}->${currentNode.process}`;
        if (!seen.has(edgeKey) && node.process !== currentNode.process) {
          seen.add(edgeKey);
          processEdges.push({ from: node.process, to: currentNode.process });
        }
      } else {
        // Continue through operators
        const nextNodes = adj.get(current) || [];
        queue.push(...nextNodes);
      }
    }
  }

  return processEdges;
}

/**
 * Find DAG file in a Nextflow run directory
 */
export async function findDagFile(runFolder: string): Promise<string | null> {
  const possiblePaths = [
    `${runFolder}/dag.dot`,
    `${runFolder}/pipeline_info/dag.dot`,
    `${runFolder}/results/pipeline_info/dag.dot`,
    `${runFolder}/dag.svg`,
    `${runFolder}/pipeline_info/dag.svg`,
  ];

  for (const p of possiblePaths) {
    try {
      await fs.access(p);
      return p;
    } catch {
      // Not found at this path
    }
  }

  return null;
}

/**
 * Get topologically sorted process order from DAG
 */
export function getTopologicalOrder(dag: NextflowDag): string[] {
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();

  // Initialize
  for (const process of dag.processNodes) {
    inDegree.set(process, 0);
    adj.set(process, []);
  }

  // Build adjacency and in-degree
  for (const edge of dag.processEdges) {
    adj.get(edge.from)?.push(edge.to);
    inDegree.set(edge.to, (inDegree.get(edge.to) || 0) + 1);
  }

  // Kahn's algorithm
  const queue: string[] = [];
  for (const [process, degree] of inDegree) {
    if (degree === 0) queue.push(process);
  }

  const sorted: string[] = [];
  while (queue.length > 0) {
    const current = queue.shift()!;
    sorted.push(current);

    for (const next of adj.get(current) || []) {
      const newDegree = (inDegree.get(next) || 1) - 1;
      inDegree.set(next, newDegree);
      if (newDegree === 0) queue.push(next);
    }
  }

  return sorted;
}
