nextflow.enable.dsl=2

params.input = null
params.outdir = 'output'
params.report_title = 'SeqDesk demo pipeline report'

process BUILD_DEMO_REPORT {
  tag "study-demo-report"

  publishDir "${params.outdir}", mode: 'copy', pattern: "report/*"
  publishDir "${params.outdir}", mode: 'copy', pattern: "tables/*"

  input:
    path samplesheet

  output:
    path "report/demo-report.html", emit: html_report
    path "report/demo-report.md", emit: markdown_report
    path "tables/sample-summary.tsv", emit: sample_summary

  script:
    """
    mkdir -p report tables

    SAMPLE_COUNT=\$(awk -F',' 'NR > 1 && \$1 != "" { c++ } END { print c + 0 }' "${samplesheet}")
    STUDY_ID=\$(awk -F',' 'NR == 2 { print \$2 }' "${samplesheet}")
    STUDY_TITLE=\$(awk -F',' 'NR == 2 { print \$3 }' "${samplesheet}")
    if [ -z "\$STUDY_TITLE" ]; then
      STUDY_TITLE="\$STUDY_ID"
    fi

    printf "sample_id\\tstudy_id\\tstudy_title\\trow_number\\n" > tables/sample-summary.tsv
    awk -F',' 'NR > 1 { printf "%s\\t%s\\t%s\\t%d\\n", \$1, \$2, \$3, NR - 1 }' "${samplesheet}" >> tables/sample-summary.tsv

    cat > report/demo-report.md <<EOF
# ${params.report_title}

Study: \$STUDY_TITLE

Samples processed: \$SAMPLE_COUNT

| Output | Purpose |
|---|---|
| demo-report.html | Browser report preview |
| demo-report.md | Markdown preview |
| sample-summary.tsv | Tabular output preview |

EOF

    cat > report/demo-report.html <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${params.report_title}</title>
  <style>
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 32px; color: #111827; }
    main { max-width: 860px; }
    h1 { font-size: 28px; margin-bottom: 8px; }
    .meta { color: #4b5563; margin-bottom: 24px; }
    table { border-collapse: collapse; width: 100%; margin-top: 16px; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; }
    th { background: #f3f4f6; }
    code { background: #f3f4f6; padding: 2px 4px; border-radius: 4px; }
  </style>
</head>
<body>
  <main>
    <h1>${params.report_title}</h1>
    <div class="meta">Study: \$STUDY_TITLE · Samples processed: \$SAMPLE_COUNT</div>
    <p>This file is generated by the SeqDesk study demo pipeline to verify pipeline execution, output discovery, preview, and download behavior.</p>
    <table>
      <thead>
        <tr><th>Artifact</th><th>Expected SeqDesk behavior</th></tr>
      </thead>
      <tbody>
        <tr><td><code>demo-report.html</code></td><td>Open as an inline HTML preview</td></tr>
        <tr><td><code>demo-report.md</code></td><td>Render as Markdown in the file browser</td></tr>
        <tr><td><code>sample-summary.tsv</code></td><td>Render as a table in the file browser</td></tr>
      </tbody>
    </table>
  </main>
</body>
</html>
EOF
    """
}

workflow {
  if (!params.input) {
    error "Missing --input samplesheet"
  }

  BUILD_DEMO_REPORT(file(params.input))
}
