/**
 * Minimal FastQC-style HTML report for the public demo.
 * Real FastQC reports are much larger; this gives a realistic preview
 * of what users see after running the FastQC pipeline.
 */
export function generateDemoFastqcReport(sampleName: string, readDirection: "R1" | "R2"): string {
  const totalSeqs = readDirection === "R1" ? "1,000,000" : "1,000,000";
  const seqLength = "150";
  const gcPercent = readDirection === "R1" ? "48" : "49";
  const dedupPercent = readDirection === "R1" ? "82.4" : "81.9";
  const title = `${sampleName}_${readDirection}`;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>FastQC Report: ${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #fff; color: #333; }
  .header { background: linear-gradient(135deg, #2c5f8a 0%, #1a3a5c 100%); color: white; padding: 24px 32px; }
  .header h1 { margin: 0 0 4px 0; font-size: 20px; font-weight: 600; }
  .header p { margin: 0; font-size: 13px; opacity: 0.85; }
  .content { max-width: 900px; margin: 0 auto; padding: 24px 32px; }
  .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  .summary-table th { text-align: left; padding: 10px 14px; background: #f7f8fa; border-bottom: 2px solid #e2e6ea; font-size: 13px; font-weight: 600; color: #555; }
  .summary-table td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 13px; }
  .summary-table tr:hover { background: #fafbfc; }
  .pass { color: #22863a; font-weight: 600; }
  .warn { color: #b08800; font-weight: 600; }
  .fail { color: #cb2431; font-weight: 600; }
  .icon { display: inline-block; width: 16px; text-align: center; margin-right: 6px; }
  .section { margin-bottom: 32px; }
  .section h2 { font-size: 16px; font-weight: 600; margin: 0 0 12px 0; padding-bottom: 8px; border-bottom: 2px solid #e2e6ea; color: #24292e; }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin-bottom: 24px; }
  .stat-card { background: #f7f8fa; border-radius: 8px; padding: 16px; }
  .stat-card .label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
  .stat-card .value { font-size: 22px; font-weight: 700; color: #24292e; }
  .chart-placeholder { background: #f7f8fa; border-radius: 8px; padding: 32px; text-align: center; color: #999; font-size: 13px; }
  .bar-chart { display: flex; align-items: flex-end; height: 120px; gap: 2px; padding: 16px; background: #f7f8fa; border-radius: 8px; }
  .bar { background: linear-gradient(180deg, #4a9eff 0%, #2c7be5 100%); border-radius: 2px 2px 0 0; flex: 1; min-width: 4px; transition: height 0.3s; }
  .demo-badge { display: inline-block; background: #fff3cd; color: #856404; font-size: 11px; padding: 2px 8px; border-radius: 4px; margin-left: 12px; font-weight: 500; }
</style>
</head>
<body>
<div class="header">
  <h1>FastQC Report: ${title} <span class="demo-badge">Demo Data</span></h1>
  <p>Generated by FastQC v0.12.1 &mdash; Demo workspace preview</p>
</div>
<div class="content">
  <div class="stat-grid">
    <div class="stat-card">
      <div class="label">Total Sequences</div>
      <div class="value">${totalSeqs}</div>
    </div>
    <div class="stat-card">
      <div class="label">Sequence Length</div>
      <div class="value">${seqLength} bp</div>
    </div>
    <div class="stat-card">
      <div class="label">%GC</div>
      <div class="value">${gcPercent}%</div>
    </div>
    <div class="stat-card">
      <div class="label">Total Deduplicated</div>
      <div class="value">${dedupPercent}%</div>
    </div>
  </div>

  <div class="section">
    <h2>Module Summary</h2>
    <table class="summary-table">
      <thead><tr><th>Module</th><th>Status</th></tr></thead>
      <tbody>
        <tr><td>Basic Statistics</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Per base sequence quality</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Per tile sequence quality</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Per sequence quality scores</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Per base sequence content</td><td><span class="icon warn">⚠</span><span class="warn">WARN</span></td></tr>
        <tr><td>Per sequence GC content</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Per base N content</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Sequence Length Distribution</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Sequence Duplication Levels</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Overrepresented sequences</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
        <tr><td>Adapter Content</td><td><span class="icon pass">✓</span><span class="pass">PASS</span></td></tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Per Base Sequence Quality</h2>
    <div class="bar-chart">
      ${Array.from({ length: 50 }, (_, i) => {
        const h = Math.min(100, 70 + Math.random() * 30 - (i > 40 ? (i - 40) * 3 : 0));
        return `<div class="bar" style="height:${h}%"></div>`;
      }).join("")}
    </div>
  </div>

  <div class="section">
    <h2>Per Sequence Quality Scores</h2>
    <div class="bar-chart">
      ${Array.from({ length: 40 }, (_, i) => {
        const peak = 36;
        const dist = Math.abs(i - peak);
        const h = Math.max(2, 100 * Math.exp(-dist * dist / 18));
        return `<div class="bar" style="height:${h}%"></div>`;
      }).join("")}
    </div>
  </div>

  <div class="section">
    <h2>Basic Statistics</h2>
    <table class="summary-table">
      <tbody>
        <tr><td>Filename</td><td>${title}.fastq.gz</td></tr>
        <tr><td>File type</td><td>Conventional base calls</td></tr>
        <tr><td>Encoding</td><td>Sanger / Illumina 1.9</td></tr>
        <tr><td>Total Sequences</td><td>${totalSeqs}</td></tr>
        <tr><td>Sequences flagged as poor quality</td><td>0</td></tr>
        <tr><td>Sequence length</td><td>${seqLength}</td></tr>
        <tr><td>%GC</td><td>${gcPercent}</td></tr>
      </tbody>
    </table>
  </div>
</div>
</body>
</html>`;
}
